export enum IconName {
    Icon123 = "123",
    Close = "close_small",
    CrisisAlert = "crisis_alert",
    DeviceHub = "device_hub",
    Favorite = "favorite",
    Group = "group",
    Info = "info",
    Key = "key",
    Logout = "logout",
    Medication = "medication",
    Menu = "menu",
    Monitor = "monitor",
    MonitorHeart = "monitor_heart",
    Person = "person",
    Refresh = "refresh",
    Schedule = "schedule",
    Settings = "settings",
    Visibility = "visibility",
    Warning = "warning",
    AccountBox = "account_box",
}